export type RoadmapType = 'backend-go' | 'backend-java' | 'fullstack';
export type ExperienceLevel = 'junior' | 'mid' | 'senior';
export type ResourceType = 'video' | 'practice' | 'project';

/**
 * Represents a specific step in the roadmap.
 */
export interface RoadmapStep {
  id: string;
  phaseId?: string; // Foreign Key to Phase
  title: string;
  type: ResourceType;
  duration: string;
  // Domain fields for backend alignment
  durationEstimate?: string; 
  resourceType: 'task' | 'topic' | 'external' | 'external_url'; 
  resourceId?: string;
  relatedResourceId?: string;
  
  status: 'locked' | 'available' | 'completed';
  link?: string;
  deepLink?: string; 
}

// For backward compatibility during refactor if needed, alias StepEntity
export type RoadmapStepEntity = RoadmapStep;

/**
 * Represents a grouping of steps.
 */
export interface RoadmapPhase {
  id: string;
  roadmapId?: string; // Foreign Key to UserRoadmap
  title: string;
  description: string;
  color: string; // Generated by frontend or stored as theme key (e.g. "blue")
  colorTheme?: string; // Alias for color in some contexts
  order: number;
  steps: RoadmapStep[];
  progress: number; // 0-100 (Calculated)
  progressPercentage?: number; // Alias
}

// Alias for Entity
export type RoadmapPhaseEntity = RoadmapPhase;

export interface UserRoadmap {
  id: string; // UUID
  userId: string; // The owner
  role: string; // e.g. "backend-go"
  roleTitle?: string;
  level: string; // e.g. "mid"
  targetLevel?: string;
  title: string; // e.g. "Mid-Level Backend Go Path"
  totalProgress: number; // 0-100
  phases: RoadmapPhase[];
  createdAt: string;
  updatedAt: string;
}

export type RoadmapEntity = UserRoadmap;

/**
 * DTO for the Frontend UI
 */
export type RoadmapStepUI = RoadmapStep;
export type RoadmapPhaseUI = RoadmapPhase;
export type RoadmapUI = UserRoadmap;
