export type RoadmapType = 'backend-go' | 'backend-java' | 'fullstack';
export type ExperienceLevel = 'junior' | 'mid' | 'senior';
export type ResourceType = 'video' | 'practice' | 'project';

// ============================================================================
// NEW: Roadmap Generation Input (Extended Wizard)
// ============================================================================

export interface RoadmapGenerationInput {
  // Step 1: Current knowledge (multi-select)
  knownLanguages: string[];
  yearsOfExperience: number;

  // Step 2: Interests (multi-select)
  interests: string[];

  // Step 3: Goal
  goal: 'first-job' | 'senior' | 'startup' | 'master-skill';

  // Step 4: Time commitment
  hoursPerWeek: number;
  targetMonths: number;
}

// ============================================================================
// NEW: Roadmap Variant (AI-generated option)
// ============================================================================

export interface RoadmapVariant {
  id: string;
  name: string;                     // "Быстрый старт", "Сбалансированный", etc.
  description: string;
  isRecommended: boolean;

  // Metrics
  totalTasks: number;
  estimatedHours: number;
  estimatedMonths: number;
  salaryRange: { min: number; max: number };
  targetRole: string;               // "Middle Go Developer"
  difficulty: 'easy' | 'medium' | 'hard';

  // Content breakdown
  topics: string[];                 // ["Go Basics", "REST APIs", ...]

  // Sources - which courses contribute tasks
  sources: {
    courseSlug: string;
    courseName: string;
    icon: string;
    taskCount: number;
    percentage: number;
  }[];

  // Preview of first few tasks
  previewTasks: {
    title: string;
    difficulty: string;
    fromCourse: string;
  }[];

  // Full phases (used after selection)
  phases?: RoadmapPhase[];
}

export interface RoadmapVariantsResponse {
  variants: RoadmapVariant[];
  canRegenerate: boolean;
  isPremium: boolean;
  generationCount: number;
}

/**
 * Represents a specific step in the roadmap.
 */
export interface RoadmapStep {
  id: string;
  phaseId?: string; // Foreign Key to Phase
  title: string;
  type: ResourceType;
  duration: string;
  // Domain fields for backend alignment
  durationEstimate?: string; 
  resourceType: 'task' | 'topic' | 'external' | 'external_url'; 
  resourceId?: string;
  relatedResourceId?: string;
  
  status: 'locked' | 'available' | 'completed';
  link?: string;
  deepLink?: string; 
}

// For backward compatibility during refactor if needed, alias StepEntity
export type RoadmapStepEntity = RoadmapStep;

/**
 * Represents a grouping of steps.
 */
export interface RoadmapPhase {
  id: string;
  roadmapId?: string; // Foreign Key to UserRoadmap
  title: string;
  description: string;
  color: string; // Generated by frontend or stored as theme key (e.g. "blue")
  colorTheme?: string; // Alias for color in some contexts
  order: number;
  steps: RoadmapStep[];
  progress: number; // 0-100 (Calculated)
  progressPercentage?: number; // Alias
}

// Alias for Entity
export type RoadmapPhaseEntity = RoadmapPhase;

export interface UserRoadmap {
  id: string; // UUID
  userId: string; // The owner
  role: string; // e.g. "backend-go"
  roleTitle?: string;
  level: string; // e.g. "mid"
  targetLevel?: string;
  title: string; // e.g. "Mid-Level Backend Go Path"
  totalProgress: number; // 0-100
  phases: RoadmapPhase[];
  createdAt: string;
  updatedAt: string;
  // Premium regeneration fields
  canRegenerate?: boolean;
  isPremium?: boolean;
  generationCount?: number;
}

export type RoadmapEntity = UserRoadmap;

/**
 * DTO for the Frontend UI
 */
export type RoadmapStepUI = RoadmapStep;
export type RoadmapPhaseUI = RoadmapPhase;
export type RoadmapUI = UserRoadmap;
